# Generated by Django 5.1.7 on 2025-03-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0002_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.FileField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
