# Generated by Django 5.1.7 on 2025-03-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0004_alter_news_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.FileField(default=1, upload_to='media/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
